site_name: CJFI
extra:
  homepage: cjfi.co.id
nav:
    - Home: index.md
    - Aplikasi:
      - Query IDER: 'aplikasi/query-iderp.md'
      - NAS Backup Depo: aplikasi/data-depo.md
    - Server:
      - Mikrotik: mikrotik.md
      - CJFI-DEV: server/cjfi-dev.md
      - CJFI: server/cjfi.md
    - Tips & Trik: 
      - Setting Samba: tutorial/setting-samba.md
theme:
  name: material
  language: id
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    scheme: default
    primary: black
    accent: yellow
  logo: logo_30.png
  features:
    - content.code.annotate
plugins:
  - macros:
      include_dir: docs/snippets

markdown_extensions:
  - abbr
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tabbed
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

